run tests:
  stage: test
  image: python:3.9
  script:
    - python -V
    - pip install -r requirements.txt
    - pip install pytest pytest-cov coverage
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
